/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Santillanes
 */
public class compartirQR extends javax.swing.JFrame {
    String usu;
    String nom;
    /**
     * Creates new form compartirQR
     */
    
    class RoundedBorder implements Border {

    private int radius;

    RoundedBorder(int radius) {
        this.radius = radius;
    }

    public Insets getBorderInsets(Component c) {
        return new Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
    }

    public boolean isBorderOpaque() {
        return true;
    }

    public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
        g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
    }
}
    
    public compartirQR(String usuario, String nombre) {
        initComponents();
        usu = usuario;
        nom = nombre;
        
        setSize(414, 896);
        this.setLocationRelativeTo(null);
        
        btnCorreo.setBorder(new RoundedBorder(30));
        btnMessenger.setBorder(new RoundedBorder(30));
        btnSalir.setBorder(new RoundedBorder(30));
        btnWhats.setBorder(new RoundedBorder(30));
        
        
    }

    private compartirQR() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnWhats = new javax.swing.JButton();
        btnMessenger = new javax.swing.JButton();
        btnCorreo = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("compartir el QR?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 198, 254, 39);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Por dónde te gustaría");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(37, 154, 340, 39);

        btnWhats.setForeground(new java.awt.Color(255, 255, 255));
        btnWhats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whats.png"))); // NOI18N
        btnWhats.setContentAreaFilled(false);
        getContentPane().add(btnWhats);
        btnWhats.setBounds(142, 301, 130, 130);

        btnMessenger.setForeground(new java.awt.Color(255, 255, 255));
        btnMessenger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/messenger.png"))); // NOI18N
        btnMessenger.setContentAreaFilled(false);
        getContentPane().add(btnMessenger);
        btnMessenger.setBounds(142, 453, 130, 130);

        btnCorreo.setForeground(new java.awt.Color(255, 255, 255));
        btnCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gmail.png"))); // NOI18N
        btnCorreo.setContentAreaFilled(false);
        btnCorreo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCorreo);
        btnCorreo.setBounds(142, 606, 130, 130);

        btnSalir.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.setContentAreaFilled(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(151, 841, 113, 33);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo2.0.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 420, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        Pantalla2 nF = new Pantalla2(usu);
        nF.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnSalirActionPerformed

    
    //################################################## ENVIAR CORREO ######################################
    correo c = new correo();
    public void enviarCorreo() throws MessagingException{
        c.setContra("ProyectoFraccionamiento");
        c.setUsuarioCorreo("Equipo2PLF@gmail.com");
        c.setAsunto("Código QR");
        c.setMensaje("¡Hola! Este es tu código QR. \nRecuerda guardarlo muy bien, ya que será tu boleto de entrada y salida del fraccionamiento.");
        c.setDestino(JOptionPane.showInputDialog("Igrese su correo electrónico: "));
        c.setNombreArchivo("CódigoQR.png");
        c.setRutaArchivo(nom);
        controlador co = new controlador();
        if (co.enviarCorreo(c)) {
            JOptionPane.showMessageDialog(null, "¡QR compartido con éxito!");
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar el mensaje.");
        }
    }
    
    
    private void btnCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorreoActionPerformed
        System.out.println(nom);
        try {
            // TODO add your handling code here:
            enviarCorreo();
        } catch (MessagingException ex) {
            System.out.println("Error al enviar: "+ex);
        }
    }//GEN-LAST:event_btnCorreoActionPerformed

    //################################################## ENVIAR CORREO ######################################
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compartirQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compartirQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compartirQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compartirQR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compartirQR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCorreo;
    private javax.swing.JButton btnMessenger;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnWhats;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
