/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import com.google.zxing.BinaryBitmap;
import com.google.zxing.ChecksumException;
import com.google.zxing.FormatException;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Reader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.mail.MessagingException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Santillanes
 */
public class detalleActivo extends javax.swing.JFrame {
    String usu, cod;
    String direccion;
    /**
     * Creates new form detalleActivo
     */
    public detalleActivo(String usuario, String codigo) throws IOException, NotFoundException, ChecksumException, FormatException {
        usu = usuario;
        cod = codigo;
        direccion = "C:\\Users\\Santillanes\\Desktop\\Prog lógica y funcional\\Equipo2_P1_U2_PLF\\Images\\"+usu+"_"+cod+".png";
        initComponents();
        
               
        
        Reader lector = new MultiFormatReader();
        File ubicacionImagen = new File(direccion);
        BufferedImage imagen;
        
        System.out.println(ubicacionImagen.getPath());
        
        if (ubicacionImagen.exists()) {
            imagen = ImageIO.read(ubicacionImagen);
            LuminanceSource fuente = new BufferedImageLuminanceSource(imagen);
            BinaryBitmap mapaBits = new BinaryBitmap(new HybridBinarizer(fuente));
            Result resultado = lector.decode(mapaBits);
            System.out.println("Detalle del codigo = "+resultado.getText());
            
            String[] resu = resultado.getText().split("\n");
            
            txtNombre.setText(resu[1]);
            txtTel.setText(resu[2]);
            txtParen.setText(resu[3]);
            txtGeneracion.setText(resu[4]);
            txtExpiracion.setText(resu[5]);
            
            lblImg.setIcon(new ImageIcon(direccion));
        }
        
        
    }

    private detalleActivo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtParen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGeneracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtExpiracion = new javax.swing.JTextField();
        lblImg = new javax.swing.JLabel();
        btnCompartir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre del visitante");

        txtNombre.setFocusable(false);

        jLabel2.setText("Teléfono del visitante");

        txtTel.setFocusable(false);

        jLabel3.setText("Parentesco del visitante");

        txtParen.setFocusable(false);

        jLabel4.setText("Fecha y hora de generación del QR");

        txtGeneracion.setFocusable(false);

        jLabel5.setText("Fecha y hora de expiración del QR");

        txtExpiracion.setFocusable(false);

        btnCompartir.setText("Compartir");
        btnCompartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompartirActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtParen, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCompartir)
                                .addGap(60, 60, 60)
                                .addComponent(btnBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnVolver)))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtParen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGeneracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtExpiracion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCompartir)
                    .addComponent(btnBorrar))
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        Activos nF = null;
        try {
            nF = new Activos(usu);
        } catch (IOException | NotFoundException | ChecksumException | FormatException ex) {
            Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
        }
        nF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCompartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompartirActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            enviarCorreo();
        } catch (MessagingException ex) {
            System.out.println("Error al enviar: "+ex);
        }
    }//GEN-LAST:event_btnCompartirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        
        if (JOptionPane.showConfirmDialog(null, "¿Estás seguro de borrar este QR?", "WARNING",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            
            String datos = "";
            try {
                // TODO add your handling code here:
                ObjectInputStream tra = new ObjectInputStream(new FileInputStream("C:\\Users\\Santillanes\\Desktop\\Prog lógica y funcional\\Equipo2_P1_U2_PLF\\DataBases\\"+usu+"QRsDataBase"));
                datos = tra.readObject().toString();
            } catch (IOException ex) {
                Logger.getLogger(detalleActivo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(detalleActivo.class.getName()).log(Level.SEVERE, null, ex);
            }

            String[] parts = datos.split("\\|");
            
            
            String direc = "C:\\Users\\Santillanes\\Desktop\\Prog lógica y funcional\\Equipo2_P1_U2_PLF\\Images\\"+usu+"_"+cod+".png";

            for (int i = 0; i < parts.length; i++) {
                if (parts[i].equals(usu+"_"+cod+".png")) {
                    File archivo = new File(direc);
                    boolean estatus = archivo.delete();
                    if (!estatus) {
                        System.out.println("Error no se ha podido eliminar el  archivo");
                    }else{
                        System.out.println("Se ha eliminado el archivo exitosamente");
                    }
                    parts[i] = "X";
                }
            }

            String nuevoDatos = "";

            for (int i = 0; i < parts.length; i++) {
                if (!("X".equals(parts[i]))) {
                    nuevoDatos += parts[i]+"|";
                }
            }

            try {
                ObjectOutputStream guar = new ObjectOutputStream(new FileOutputStream("C:\\Users\\Santillanes\\Desktop\\Prog lógica y funcional\\Equipo2_P1_U2_PLF\\DataBases\\"+usu+"QRsDataBase"));
                guar.writeObject(nuevoDatos);
                System.out.println("guar = " + guar);
            } catch (IOException ex) {
                Logger.getLogger(detalleActivo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showMessageDialog(null, "QR borrado con éxito.");
            Activos nF = null;
            try {
                nF = new Activos(usu);
            } catch (IOException | NotFoundException | ChecksumException | FormatException ex) {
                Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
            }
            nF.setVisible(true);
            this.dispose();
            
        } else {
            
        }
        
        
    }//GEN-LAST:event_btnBorrarActionPerformed

    //################################################## ENVIAR CORREO ######################################
    correo c = new correo();
    
    
    public void enviarCorreo() throws MessagingException{
        System.out.println("direccion = " + direccion);
        System.out.println("direccion = " + direccion);
        c.setContra("ProyectoFraccionamiento");
        c.setUsuarioCorreo("Equipo2PLF@gmail.com");
        c.setAsunto("Código QR");
        c.setMensaje("¡Hola! Este es tu código QR. \nRecuerda guardarlo muy bien, ya que será tu boleto de entrada y salida del fraccionamiento.");
        c.setDestino(JOptionPane.showInputDialog("Igrese su correo electrónico: "));
        c.setNombreArchivo("CódigoQR.png");
        c.setRutaArchivo(direccion);
        controlador co = new controlador();
        if (co.enviarCorreo(c)) {
            JOptionPane.showMessageDialog(null, "¡QR compartido con éxito!");
        }else{
            JOptionPane.showMessageDialog(null, "Error al enviar el mensaje.");
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detalleActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detalleActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detalleActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detalleActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detalleActivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCompartir;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblImg;
    private javax.swing.JTextField txtExpiracion;
    private javax.swing.JTextField txtGeneracion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtParen;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
