package Proyecto;

import com.google.zxing.BarcodeFormat;
import com.google.zxing.ChecksumException;
import com.google.zxing.FormatException;
import com.google.zxing.NotFoundException;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Santillanes
 */



public class Pantalla2 extends javax.swing.JFrame {
    String usuario;
    /**
     * Creates new form Pantalla2
     */
    public Pantalla2(String usu) {
        initComponents();
        
        setSize(414, 896);
        this.setLocationRelativeTo(null);
        
        lblWelcome.setText("¡Bienvenido, " + usu + "!");
        lblWelcome.setForeground(Color.WHITE);
        
        usuario = usu;
        
        btnCrear.setBorder(new RoundedBorder(30));
        btnActivos.setBorder(new RoundedBorder(30));
        btnCerrarSesion.setBorder(new RoundedBorder(30));
        btnEditPerfil.setBorder(new RoundedBorder(30));
    }

    private Pantalla2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWelcome = new javax.swing.JLabel();
        btnActivos = new javax.swing.JButton();
        btnEditPerfil = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        lblWelcome.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWelcome.setText("lblWelcome");
        getContentPane().add(lblWelcome);
        lblWelcome.setBounds(64, 216, 286, 39);

        btnActivos.setFont(new java.awt.Font("Yu Gothic UI", 1, 15)); // NOI18N
        btnActivos.setForeground(new java.awt.Color(255, 255, 255));
        btnActivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr activos.png"))); // NOI18N
        btnActivos.setText("QR Activos");
        btnActivos.setContentAreaFilled(false);
        btnActivos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActivos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivosActionPerformed(evt);
            }
        });
        getContentPane().add(btnActivos);
        btnActivos.setBounds(224, 320, 146, 146);

        btnEditPerfil.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnEditPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnEditPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/VER PERFIL.png"))); // NOI18N
        btnEditPerfil.setText("Ver Perfil");
        btnEditPerfil.setContentAreaFilled(false);
        btnEditPerfil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditPerfil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditPerfil);
        btnEditPerfil.setBounds(44, 500, 146, 146);

        btnCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarSesion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion);
        btnCerrarSesion.setBounds(224, 500, 146, 146);

        btnCrear.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        btnCrear.setForeground(new java.awt.Color(255, 255, 255));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/qr.png"))); // NOI18N
        btnCrear.setText("Crear QR");
        btnCrear.setContentAreaFilled(false);
        btnCrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear);
        btnCrear.setBounds(44, 320, 146, 146);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo 414x986 4.0.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 415, 896);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        
        CrearQR nF = new CrearQR(usuario);
        nF.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        
        login nF = new login();
        nF.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEditPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPerfilActionPerformed
        
        VerPerfil nF = new VerPerfil(usuario);
        nF.setVisible(true);
        this.dispose();
       
    }//GEN-LAST:event_btnEditPerfilActionPerformed

    private void btnActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivosActionPerformed
        
        Activos nF = null;
        try {
            nF = new Activos(usuario);
        } catch (IOException ex) {
            Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotFoundException ex) {
            Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ChecksumException ex) {
            Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FormatException ex) {
            Logger.getLogger(Pantalla2.class.getName()).log(Level.SEVERE, null, ex);
        }
        nF.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_btnActivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivos;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEditPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
